### ISSUE TITLE
Примеры использования

### ISSUE THREAD

**Issue by khmelev77** [luminosoda/anypay#1]
Hello, great library. Can i see examples of using this library? Otherwise, I don't quite understand how to call methods, besides, they are also asynchronous.
Thanks. (Google Translate with corrections)

Здравствуйте, отличная библиотека. Можно увидеть примеры использования этой библиотеки? А то не совсем понимаю, как вызывать методы, к тому же они еще и асинхронные.
Спасибо.

**Comment by luminosoda** [comment]
> Can i see examples of using this library?

The simplest example of getting a balance:

> Можно увидеть примеры использования этой библиотеки?

Простейший пример получения баланса:
```Python
anypay = AnyPay(id_="API ID", key="API key")

balance = await anypay.balance()
print(f"Balance: {balance}")
```

**Comment by luminosoda** [comment]
I don't have time to deal with this library now, a bit later I'll make README.md, add examples and release it to PyPI.

Сейчас на эту библиотеку нету времени, чуть позже оформлю README.md, добавлю примеров и релизну в PyPI.
